### ISSUE TITLE
Error:Execution failed for task ':app:transformClassesWithDexForDebug'.

### ISSUE THREAD

**Issue by udasibharat1** [varvet/BarcodeReaderSample#1]
Error:Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException

**Comment by udasibharat1** [comment]
this issue come when i import the project

**Comment by daniellAlgar** [comment]
@udasibharat1 What Android Studio version are you running?

**Comment by udasibharat1** [comment]
I solved the issue by changing its minimum required SDK...,minify enabled,
multidex
