### ISSUE TITLE
Flashlight problems

### ISSUE THREAD

**Issue by jajcelol1** [varvet/BarcodeReaderSample#3]
How do i turn on the flashlight when i m in the camera?  I have tried to turn the flashlight before clicking the button but when the camera launches the flashlight turns off.

**Comment by daniellAlgar** [comment]
@jajcelol1 This isn't an issue but rather a feature request. 

You will have to add that functionality yourself.

Inside `BarcodeCaptureActivity` you can add a menu item in the `onCreateOptionsMenu`, i.e.

    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        getMenuInflater().inflate(R.menu.menu_flashlight, menu);
        mMenuItem = menu.findItem(R.id.menu_flashlight);

        if (!deviceSupportsFlashlight()) {
            mMenuItem.setIcon(R.drawable.flashlight_disabled);
            mMenuItem.setOnMenuItemClickListener(new MenuItem.OnMenuItemClickListener() {
                @Override
                public boolean onMenuItemClick(MenuItem menuItem) {
                    Toast.makeText(BarcodeCaptureActivity.this, R.string.no_flashlight_on_device_toast,
                            Toast.LENGTH_SHORT).show();
                    return true;
                }
            });
        }

        return true;
    }

where `R.menu.menu_flashlight` might look like 

    <?xml version="1.0" encoding="utf-8"?>
    <menu
        xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:app="http://schemas.android.com/apk/res-auto">
        <item
            android:id="@+id/menu_flashlight"
            android:title="@string/menu_flashlight"
            android:icon="@drawable/flashlight_on"
            app:showAsAction="always" />
    </menu>

and

    private boolean deviceSupportsFlashlight() {
        return getApplicationContext().getPackageManager()
                .hasSystemFeature(PackageManager.FEATURE_CAMERA_FLASH);
    }

Then as always you can check in `onOptionsItemSelected()` that the flash icon was clicked

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        int id = item.getItemId();

        if (id == R.id.menu_flashlight) {
            toggleFlashlight();
            return true;
        }
        return super.onOptionsItemSelected(item);
    }

where 

    private void toggleFlashlight() {
        if (deviceSupportsFlashlight()) {
            if (mCameraSource.getFlashMode().equals(Camera.Parameters.FLASH_MODE_TORCH)) {
                mCameraSource.setFlashMode(Camera.Parameters.FLASH_MODE_OFF);
                mMenuItem.setIcon(R.drawable.flashlight_on);
            } else {
                mCameraSource.setFlashMode(Camera.Parameters.FLASH_MODE_TORCH);
                mMenuItem.setIcon(R.drawable.flashlight_off);
            }
        }
    }

**Comment by jajcelol1** [comment]
I see , thank you. You can close this.
